name: bolsa_empleo
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: srdraka <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_forms: ^1.0.0
  angular_router: ^1.0.2
  http: ^0.11.0
  stream_transform: ^0.0.6
  mdl: ^2.0.3
  dice: ^1.7.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular:
    entry_points: web/main.dart
- dart_to_js_script_rewriter